[2023-06-04T08:08:58.911+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: most_popular_movies.load_movies manual__2023-06-04T08:08:52.836063+00:00 [queued]>
[2023-06-04T08:08:58.916+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: most_popular_movies.load_movies manual__2023-06-04T08:08:52.836063+00:00 [queued]>
[2023-06-04T08:08:58.917+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2023-06-04T08:08:58.926+0000] {taskinstance.py:1327} INFO - Executing <Task(_PythonDecoratedOperator): load_movies> on 2023-06-04 08:08:52.836063+00:00
[2023-06-04T08:08:58.930+0000] {standard_task_runner.py:57} INFO - Started process 339 to run task
[2023-06-04T08:08:58.933+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'most_popular_movies', 'load_movies', 'manual__2023-06-04T08:08:52.836063+00:00', '--job-id', '57', '--raw', '--subdir', 'DAGS_FOLDER/most_popular_movies.py', '--cfg-path', '/tmp/tmpfkxegae2']
[2023-06-04T08:08:58.934+0000] {standard_task_runner.py:85} INFO - Job 57: Subtask load_movies
[2023-06-04T08:08:58.964+0000] {task_command.py:410} INFO - Running <TaskInstance: most_popular_movies.load_movies manual__2023-06-04T08:08:52.836063+00:00 [running]> on host 7633a4fabdb3
[2023-06-04T08:08:59.087+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='most_popular_movies' AIRFLOW_CTX_TASK_ID='load_movies' AIRFLOW_CTX_EXECUTION_DATE='2023-06-04T08:08:52.836063+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-06-04T08:08:52.836063+00:00'
[2023-06-04T08:08:59.094+0000] {logging_mixin.py:149} INFO - Fetching Dataset...
[2023-06-04T08:08:59.737+0000] {logging_mixin.py:149} INFO - Done
[2023-06-04T08:08:59.737+0000] {logging_mixin.py:149} INFO - https://bigquery.googleapis.com/bigquery/v2/projects/imdb-388708/datasets/imdb
[2023-06-04T08:08:59.737+0000] {logging_mixin.py:149} INFO - 
Fetching Table...
[2023-06-04T08:09:00.036+0000] {logging_mixin.py:149} INFO - Done
[2023-06-04T08:09:00.036+0000] {logging_mixin.py:149} INFO - https://bigquery.googleapis.com/bigquery/v2/projects/imdb-388708/datasets/imdb/tables/most_popular_movies
[2023-06-04T08:09:00.036+0000] {logging_mixin.py:149} INFO - 
Loading data into BigQuery...
[2023-06-04T08:09:05.189+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/decorators/base.py", line 220, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/most_popular_movies.py", line 36, in load_movies
    _load_bigQuery_most_popular_movies(movies_df)
  File "/opt/airflow/dags/helper/web_scrape.py", line 211, in _load_bigQuery_most_popular_movies
    load_job.result()
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery/job/base.py", line 728, in result
    return super(_AsyncJob, self).result(timeout=timeout, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/api_core/future/polling.py", line 137, in result
    raise self._exception
google.api_core.exceptions.BadRequest: 400 Error while reading data, error message: CSV table references column position 3, but line starting at position:23 contains only 1 columns.
[2023-06-04T08:09:05.196+0000] {taskinstance.py:1350} INFO - Marking task as FAILED. dag_id=most_popular_movies, task_id=load_movies, execution_date=20230604T080852, start_date=20230604T080858, end_date=20230604T080905
[2023-06-04T08:09:05.206+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 57 for task load_movies (400 Error while reading data, error message: CSV table references column position 3, but line starting at position:23 contains only 1 columns.; 339)
[2023-06-04T08:09:05.234+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-06-04T08:09:05.245+0000] {taskinstance.py:2651} INFO - 0 downstream tasks scheduled from follow-on schedule check
